plugins {
    id 'fabric-loom' version "${fabric_loom_version}"
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

base {
    archivesName = artifact_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://maven.blamejared.com' }
    maven {
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    modImplementation(include("maven.modrinth:forge-config-api-port:${forge_config_api_port_version}"))
    implementation(include("com.electronwill.night-config:core:${night_config_version}"))
    implementation(include("com.electronwill.night-config:toml:${night_config_version}"))
    modImplementation(include("teamreborn:energy:${team_reborn_energy_version}"))

    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
    modLocalRuntime "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
    testImplementation "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    testImplementation "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"

    testImplementation platform("org.junit:junit-bom:5.12.1")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    testImplementation "org.mockito:mockito-core:5.16.1"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            mod_id           : mod_id,
            mod_name         : mod_name,
            mod_license      : mod_license,
            mod_version      : mod_version,
            minecraft_version: minecraft_version,
            loader_version   : loader_version,
            java_version     : java_version
    ]
    inputs.properties replaceProperties

    filesMatching(['fabric.mod.json']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
            artifactId = artifact_name
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = java_version as int
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(
                'Implementation-Title': artifact_name,
                'Specification-Title': artifact_name
        )
    }
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}
