org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=false

minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.42
forge_version_range=[36,)
loader_version_range=[36,)
mapping_channel=official
mapping_version=1.16.5

jei_version=7.8.1.1018
ae2_version=8.4.7
mekanism_version=1.16.5-10.1.2.457
mekanism_version_range=[10.1,)

mod_id=deepnullreforged
artifact_name=deepnull-reforged-1.16.5
mod_name=DeepNull Reforged
mod_license=MIT
mod_version=4.2.1
mod_group_id=dev.deepdaddyttv.deepnullreforged
mod_authors=DeepDaddyTTV
mod_description=DeepNull Reforged brings tiered portable item, fluid, and energy storage to Minecraft 1.16.5.
